name: Build & Publish Peticoes (web + api)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute lowercase owner for GHCR
        run: echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV
        env:
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}

      # WEB ---------------------------------------------------------------
      - name: Build & Push web
        uses: docker/build-push-action@v6
        with:
          context: ./web
          file: ./web/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/peticoes-web:main
            ghcr.io/${{ env.OWNER_LC }}/peticoes-web:${{ github.sha }}

      # API ---------------------------------------------------------------
      - name: Build & Push api
        uses: docker/build-push-action@v6
        with:
          context: ./api
          file: ./api/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/peticoes-api:main
            ghcr.io/${{ env.OWNER_LC }}/peticoes-api:${{ github.sha }}
