name: Build & Publish Peticoes (web + api)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io
      OWNER: ${{ github.repository_owner }}
      IMAGE_WEB: ghcr.io/${{ github.repository_owner }}/peticoes-web
      IMAGE_API: ghcr.io/${{ github.repository_owner }}/peticoes-api
      SHORT_SHA: ${{ github.sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # WEB ---------------------------------------------------------------
      - name: Build & Push web
        uses: docker/build-push-action@v6
        with:
          context: ./web
          file: ./web/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_WEB }}:main
            ${{ env.IMAGE_WEB }}:${{ env.SHORT_SHA }}

      # API ---------------------------------------------------------------
      - name: Build & Push api
        uses: docker/build-push-action@v6
        with:
          context: ./api
          file: ./api/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_API }}:main
            ${{ env.IMAGE_API }}:${{ env.SHORT_SHA }}
